schema: http://localhost:5000
documents: src/**/*.graphql
extensions:
  codegen:
    generates:
      src/generated/graphql.ts:
        plugins:
          - typescript
          - typescript-operations
          - typescript-urql
        config:
          withComponent: false
          withHooks: true
